# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
  If you are first time visiting this repo please Read this document carefully and please complete the [Onboarding Process](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki/Contributor-Onboarding) and if you want to start working please comment on the issue first and setup the project locally and read the [Commit Message Styling guide](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki/Commit-Message-Styling-Guide) and if you are a maintainer please Read [Maintainer Guide](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki/Maintainer-Guidelines)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ§‘â€ğŸ’»ğŸ‘©â€ğŸ’» Thanks for opening this pull request! Please check out our contributing guidelines.ğŸ¥³ğŸ¥³
  Please be patient our project maintainers will get back to you soon and till then you can find differenct issues listed [here](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues)
  And Please make sure you have completed the [Onboarding Process](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/wiki/Contributor-Onboarding).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ¥³ğŸ¥³Congrats on merging your first pull request! We here at HotelOnTouch are proud of you!ğŸ‰ğŸ‰ğŸ‰

# It is recommended to include as many gifs and emojis as possible!
